const lessonTitle = "老师，我站着呢！";

const lessonData = [
    // ===== 第1段 =====
    ["这是", "zhè shì", "This is", "Ini adalah"],
    ["一所", "yì suǒ", "a", "sebuah"],
    ["能", "néng", "can", "boleh"],
    ["看到大海", "kàn dào dà hǎi", "see the sea", "melihat laut"],
    ["的", "de", "", ""],
    ["地势较高", "dì shì jiào gāo", "high-altitude", "berkedudukan tinggi"],
    ["的", "de", "", ""],
    ["中学", "zhōng xué", "middle school", "sekolah menengah"],
    ["，", "", "", ""],
    ["上课时", "shàng kè shí", "during class", "semasa kelas"],
    ["从教室", "cóng jiào shì", "from the classroom", "dari bilik darjah"],
    ["就能", "jiù néng", "can", "boleh"],
    ["看到", "kàn dào", "see", "melihat"],
    ["变化无穷", "biàn huà wú qióng", "ever-changing", "sentiasa berubah"],
    ["的", "de", "", ""],
    ["大海", "dà hǎi", "sea", "laut"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["那年", "nà nián", "That year", "Tahun itu"],
    ["约有", "yuē yǒu", "there were about", "kira-kira ada"],
    ["80名", "bā shí míng", "80", "80 orang"],
    ["新生", "xīn shēng", "new students", "pelajar baharu"],
    ["入学", "rù xué", "enrolled", "masuk sekolah"],
    ["，", "", "", ""],
    ["其中", "qí zhōng", "among them", "antaranya"],
    ["大多数", "dà duō shù", "most", "kebanyakan"],
    ["是", "shì", "were", "ialah"],
    ["那些", "nà xiē", "those", "mereka"],
    ["与大海搏击", "yǔ dà hǎi bó jī", "fight the sea", "bergelut dengan laut"],
    ["的", "de", "", ""],
    ["渔民们", "yú mín men", "fishermen", "nelayan-nelayan"],
    ["的", "de", "", ""],
    ["子弟", "zǐ dì", "children", "anak-anak"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["那", "nà", "That", "Itu"],
    ["是", "shì", "was", "ialah"],
    ["我", "wǒ", "I", "saya"],
    ["给", "gěi", "to", "kepada"],
    ["新生上", "xīn shēng shàng", "teaching new students", "mengajar pelajar baharu"],
    ["的", "de", "", ""],
    ["第一堂课", "dì yī táng kè", "first lesson", "pelajaran pertama"],
    ["的", "de", "", ""],
    ["事情", "shì qing", "matter", "perkara"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["“", "", "", ""],
    ["起立", "qǐ lì", "Stand up", "Berdiri"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["大家都", "dà jiā dōu", "Everyone", "Semua orang"],
    ["站起来了", "zhàn qǐ lái le", "stood up", "berdiri"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["是新生", "shì xīn shēng", "they were new students", "mereka pelajar baharu"],
    ["，", "", "", ""],
    ["所以", "suǒ yǐ", "so", "jadi"],
    ["都很认真", "dōu hěn rèn zhēn", "very serious", "sangat serius"],
    ["，", "", "", ""],
    ["教室", "jiào shì", "the classroom", "bilik darjah"],
    ["出现", "chū xiàn", "appeared", "muncul"],
    ["瞬间", "shùn jiān", "a moment of", "seketika"],
    ["的", "de", "", ""],
    ["寂静", "jì jìng", "silence", "kesunyian"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["但是", "dàn shì", "But", "Tetapi"],
    ["，", "", "", ""],
    ["有一名", "yǒu yì míng", "there was a", "ada seorang"],
    ["学生", "xué sheng", "student", "pelajar"],
    ["耍滑头", "shuǎ huá tóu", "playing tricks", "bermain helah"],
    ["，", "", "", ""],
    ["未起立", "wèi qǐ lì", "did not stand up", "tidak berdiri"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    ["“", "", "", ""],
    ["站起来", "zhàn qǐ lái", "Stand up", "Berdiri"],
    ["，", "", "", ""],
    ["刚入学", "gāng rù xué", "just enrolled", "baru masuk sekolah"],
    ["就是", "jiù shì", "already", "sudah"],
    ["这种态度", "zhè zhǒng tài dù", "this attitude", "sikap begini"],
    ["可不行", "kě bù xíng", "not acceptable", "tidak boleh"],
    ["！”", "", "", ""],
    ["我的", "wǒ de", "My", "Saya punya"],
    ["语气", "yǔ qì", "tone", "nada suara"],
    ["顿时", "dùn shí", "suddenly", "serta-merta"],
    ["严厉起来", "yán lì qǐ lái", "became stern", "menjadi tegas"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    ["这时", "zhè shí", "At this moment", "Pada masa ini"],
    ["，", "", "", ""],
    ["传来", "chuán lái", "came", "datang"],
    ["一个声音", "yí gè shēng yīn", "a voice", "sebuah suara"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["老师", "lǎo shī", "Teacher", "Guru"],
    ["，", "", "", ""],
    ["我站着呢", "wǒ zhàn zhe ne", "I am standing", "Saya sedang berdiri"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    ["是的", "shì de", "Yes", "Ya"],
    ["，", "", "", ""],
    ["他", "tā", "He", "Dia"],
    ["，", "", "", ""],
    ["A君", "A jūn", "Student A", "Pelajar A"],
    ["站着", "zhàn zhe", "was standing", "sedang berdiri"],
    ["，", "", "", ""],
    ["但是", "dàn shì", "but", "tetapi"],
    ["由于", "yóu yú", "because", "kerana"],
    ["他个子太矮", "tā gè zi tài ǎi", "he was too short", "dia terlalu pendek"],
    ["，", "", "", ""],
    ["我看着", "wǒ kàn zhe", "I looked like", "saya nampak seperti"],
    ["像是坐着", "xiàng shì zuò zhe", "sitting", "sedang duduk"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    ["糟糕", "zāo gāo", "Oh no", "Teruknya"],
    ["！", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["做了", "zuò le", "did", "telah melakukan"],
    ["对不起", "duì bù qǐ", "wronged", "menzalimi"],
    ["A君", "A jūn", "Student A", "Pelajar A"],
    ["的", "de", "", ""],
    ["事", "shì", "thing", "perkara"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    ["我", "wǒ", "I", "Saya"],
    ["为自己的", "wèi zì jǐ de", "for my own", "untuk diri sendiri punya"],
    ["粗心", "cū xīn", "carelessness", "kecuaian"],
    ["感到不安", "gǎn dào bù ān", "felt uneasy", "berasa gelisah"],
    ["，", "", "", ""],
    ["一时", "yī shí", "for a moment", "seketika"],
    ["竟", "jìng", "actually", "sebenarnya"],
    ["不知", "bù zhī", "didn't know", "tidak tahu"],
    ["说什么才好", "shuō shén me cái hǎo", "what to say", "apa nak cakap"],
    ["。", "", "", ""],
    ["如果", "rú guǒ", "If", "Jika"],
    ["在此时", "zài cǐ shí", "at this moment", "pada masa ini"],
    ["道歉", "dào qiàn", "apologize", "minta maaf"],
    ["，", "", "", ""],
    ["反而", "fǎn ér", "instead", "sebaliknya"],
    ["会伤了", "huì shāng le", "would hurt", "akan menyakiti"],
    ["A君", "A jūn", "Student A's", "Pelajar A punya"],
    ["的", "de", "", ""],
    ["自尊心", "zì zūn xīn", "self-esteem", "maruah diri"],
    ["。", "", "", ""],
    ["于是", "yú shì", "So", "Maka"],
    ["，", "", "", ""],
    ["我当时", "wǒ dāng shí", "at that time", "pada masa itu"],
    ["只说了声", "zhǐ shuō le shēng", "only said", "hanya berkata"],
    ["“", "", "", ""],
    ["对不起", "duì bù qǐ", "Sorry", "Maaf"],
    ["”", "", "", ""],
    ["。", "", "", ""],
    ["周围的", "zhōu wéi de", "The surrounding", "Sekeliling"],
    ["学生", "xué sheng", "students", "pelajar-pelajar"],
    ["都笑起来", "dōu xiào qǐ lái", "all laughed", "semua ketawa"],
    ["。", "", "", ""],
    ["A君的", "A jūn de", "Student A's", "Pelajar A punya"],
    ["心情", "xīn qíng", "mood", "perasaan"],
    ["一定", "yí dìng", "must", "pasti"],
    ["很难受", "hěn nán shòu", "very uncomfortable", "sangat tidak selesa"],
    ["，", "", "", ""],
    ["我意识到", "wǒ yì shí dào", "I realized", "saya sedar"],
    ["A君", "A jūn", "Student A", "Pelajar A"],
    ["以后", "yǐ hòu", "in the future", "pada masa depan"],
    ["也许", "yě xǔ", "maybe", "mungkin"],
    ["会因为", "huì yīn wèi", "would because of", "akan kerana"],
    ["这件事", "zhè jiàn shì", "this matter", "perkara ini"],
    ["受他人的", "shòu tā rén de", "be bullied by others", "dibuli oleh orang lain"],
    ["欺侮", "qī wǔ", "bullying", "buli"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    ["下课后", "xià kè hòu", "After class", "Selepas kelas"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["本想", "běn xiǎng", "had intended to", "berniat untuk"],
    ["向A君道歉", "xiàng A jūn dào qiàn", "apologize to Student A", "minta maaf kepada Pelajar A"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["忙乱之中", "máng luàn zhī zhōng", "in the busyness", "dalam kesibukan"],
    ["竟", "jìng", "actually", "sebenarnya"],
    ["把此事", "bǎ cǐ shì", "this matter", "perkara ini"],
    ["忘了", "wàng le", "forgot", "lupa"],
    ["。", "", "", ""],
    ["晚上", "wǎn shàng", "In the evening", "Pada waktu malam"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["犹豫着", "yóu yù zhe", "hesitated", "teragak-agak"],
    ["是否", "shì fǒu", "whether", "sama ada"],
    ["给A君打电话", "gěi A jūn dǎ diàn huà", "to call Student A", "menelefon Pelajar A"],
    ["。", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["打电话道歉", "dǎ diàn huà dào qiàn", "apologizing by phone", "minta maaf melalui telefon"],
    ["太不礼貌", "tài bù lǐ mào", "too impolite", "terlalu tidak sopan"],
    ["，", "", "", ""],
    ["于是", "yú shì", "so", "maka"],
    ["只好作罢", "zhǐ hǎo zuò bà", "had to give up", "terpaksa membatalkan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第13段

    ["第二天", "dì èr tiān", "The next day", "Keesokan harinya"],
    ["，", "", "", ""],
    ["天空", "tiān kōng", "the sky", "langit"],
    ["晴朗无云", "qíng lǎng wú yún", "clear and cloudless", "cerah dan tiada awan"],
    ["，", "", "", ""],
    ["春天", "chūn tiān", "spring", "musim bunga"],
    ["的", "de", "", ""],
    ["大海", "dà hǎi", "sea", "laut"],
    ["碧波荡漾", "bì bō dàng yàng", "blue waves rippling", "ombak biru berkilauan"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["给", "gěi", "to", "kepada"],
    ["A君", "A jūn", "Student A's", "Pelajar A punya"],
    ["的班上", "de bān shàng", "class", "kelas"],
    ["第二堂课", "dì èr táng kè", "second lesson", "pelajaran kedua"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第14段

    ["“", "", "", ""],
    ["起立", "qǐ lì", "Stand up", "Berdiri"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第15段

    ["又是", "yòu shì", "Again", "Sekali lagi"],
    ["瞬间", "shùn jiān", "a moment of", "seketika"],
    ["的", "de", "", ""],
    ["寂静", "jì jìng", "silence", "kesunyian"],
    ["。", "", "", ""],
    ["这时", "zhè shí", "At this moment", "Pada masa ini"],
    ["，", "", "", ""],
    ["忽然", "hū rán", "suddenly", "tiba-tiba"],
    ["传来", "chuán lái", "came", "datang"],
    ["一个", "yí gè", "a", "sebuah"],
    ["洪亮的声音", "hóng liàng de shēng yīn", "loud voice", "suara yang lantang"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["老师", "lǎo shī", "Teacher", "Guru"],
    ["，", "", "", ""],
    ["我站着呢", "wǒ zhàn zhe ne", "I am standing", "Saya sedang berdiri"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第16段

    ["是", "shì", "It was", "Ia adalah"],
    ["A君", "A jūn", "Student A", "Pelajar A"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["站在椅子上", "zhàn zài yǐ zi shàng", "standing on the chair", "berdiri di atas kerusi"],
    ["，", "", "", ""],
    ["微笑着", "wēi xiào zhe", "smiling", "tersenyum"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第17段

    ["从", "cóng", "From", "Daripada"],
    ["A君的", "A jūn de", "Student A's", "Pelajar A punya"],
    ["微笑中", "wēi xiào zhōng", "smile", "senyuman"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["看出", "kàn chū", "saw", "nampak"],
    ["他", "tā", "he", "dia"],
    ["这样做", "zhè yàng zuò", "doing this", "buat begini"],
    ["并不是", "bìng bú shì", "was not", "bukan"],
    ["讽刺", "fěng cì", "sarcasm", "sindiran"],
    ["，", "", "", ""],
    ["也不是", "yě bú shì", "nor", "juga bukan"],
    ["抵抗情绪", "dǐ kàng qíng xù", "resistance", "perasaan menentang"],
    ["的", "de", "", ""],
    ["表露", "biǎo lù", "expression", "penzahiran"],
    ["。", "", "", ""],
    ["我感到了", "wǒ gǎn dào le", "I felt", "saya rasa"],
    ["“", "", "", ""],
    ["老师", "lǎo shī", "Teacher", "Guru"],
    ["，", "", "", ""],
    ["我不在意", "wǒ bù zài yì", "I don't mind", "Saya tidak kisah"],
    ["，", "", "", ""],
    ["不要为我担心", "bú yào wèi wǒ dān xīn", "don't worry about me", "jangan risau tentang saya"],
    ["”", "", "", ""],
    ["这样一种体谅", "zhè yàng yì zhǒng tǐ liàng", "such understanding", "pemahaman begini"],
    ["，", "", "", ""],
    ["我的", "wǒ de", "my", "saya punya"],
    ["心口", "xīn kǒu", "heart", "hati"],
    ["感到", "gǎn dào", "felt", "merasa"],
    ["一阵疼痛", "yí zhèn téng tòng", "a pang of pain", "sakit yang menusuk"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第18段

    ["晚上", "wǎn shàng", "In the evening", "Pada waktu malam"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["怀着", "huái zhe", "with", "dengan"],
    ["复杂的心情", "fù zá de xīn qíng", "complicated feelings", "perasaan yang rumit"],
    ["给", "gěi", "to", "kepada"],
    ["A君", "A jūn", "Student A", "Pelajar A"],
    ["拨了电话", "bō le diàn huà", "made a phone call", "menelefon"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第19段

    ["“", "", "", ""],
    ["老师", "lǎo shī", "Teacher", "Guru"],
    ["，", "", "", ""],
    ["别在意", "bié zài yì", "Don't mind", "Jangan kisah"],
    ["，", "", "", ""],
    ["别在意", "bié zài yì", "don't mind", "jangan kisah"],
    ["！”", "", "", ""],
    ["对面", "duì miàn", "from the other end", "dari sebelah sana"],
    ["传来", "chuán lái", "came", "datang"],
    ["A君", "A jūn", "Student A's", "Pelajar A punya"],
    ["爽朗", "shuǎng lǎng", "cheerful", "ceria"],
    ["又", "yòu", "and", "dan"],
    ["充满稚气", "chōng mǎn zhì qì", "childish", "penuh dengan sifat kebudak-budakan"],
    ["的", "de", "", ""],
    ["声音", "shēng yīn", "voice", "suara"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第20段

    ["我", "wǒ", "I", "Saya"],
    ["期盼", "qī pàn", "hoped", "berharap"],
    ["明天的天空", "míng tiān de tiān kōng", "tomorrow's sky", "langit esok"],
    ["还是", "hái shì", "still", "masih"],
    ["晴朗无云", "qíng lǎng wú yún", "clear and cloudless", "cerah dan tiada awan"],
    ["，", "", "", ""],
    ["大海", "dà hǎi", "the sea", "laut"],
    ["还是", "hái shì", "still", "masih"],
    ["碧波荡漾", "bì bō dàng yàng", "blue waves rippling", "ombak biru berkilauan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["不详", "bù xiáng", "Unknown", "Tidak diketahui"],
    ["《", "", "", ""],
    ["老师，我站着呢！", "lǎo shī，wǒ zhàn zhe ne！", "Teacher, I'm Standing!", "Cikgu, Saya Berdiri!"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
